{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "#your code here\n",
    "    if a > b:\n",
    "        return a\n",
    "    else:\n",
    "        return b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.079s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "\n",
    "def greatest(lst):\n",
    "    if not lst:\n",
    "        return None\n",
    "    maxval = lst[0]\n",
    "    for i in lst:\n",
    "        if i > maxval:\n",
    "            maxval = i\n",
    "    return maxval"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.056s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(lst):\n",
    "#your code here\n",
    "    s = 0\n",
    "    for i in lst:\n",
    "        s += i\n",
    "    return s"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.036s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(lst):\n",
    "#your code here\n",
    "    mul = 1\n",
    "    for i in lst:\n",
    "        mul *= i\n",
    "    return mul"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.037s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'if' statement on line 6 (2640325370.py, line 8)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[102], line 8\u001b[1;36m\u001b[0m\n\u001b[1;33m    return sum_all(arr)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m expected an indented block after 'if' statement on line 6\n"
     ]
    }
   ],
   "source": [
    "def oper_all(arr, oper = \"*\"):\n",
    "#your code here\n",
    "    if not arr:\n",
    "        return None\n",
    "    else:\n",
    "        if oper == \"+\":\n",
    "        \n",
    "        return sum_all(arr)\n",
    "    else oper == \"*\":\n",
    "        return mult_all"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "#your code here\n",
    "    c = 1\n",
    "    i = 1\n",
    "    while i <= n:\n",
    "        c *= i\n",
    "        i += 1 \n",
    "    return c"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#factorial formula\n",
    "#n! = n * ( n - 1 ) *...*1\n",
    "\n",
    "# This code defines a function called \"factorial\" which takes an input \"n\". The function uses a for loop to iterate through the range of numbers \n",
    "# from 1 to n+1. For each number in that range, it multiplies the current value of x by the number in the range. At the end of the loop, \n",
    "# the function returns the final value of x, which will be the factorial of the input number \"n\".\n",
    "\n",
    "# The Factorial of a positive integer n is the product of all positive integers less than or equal to n. \n",
    "# For example, the factorial of 6 (written \"6!\") is 6 * 5 * 4 * 3 * 2 * 1 = 720.\n",
    "\n",
    "# So this function takes an input of any positive integer, and returns the factorial of that number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.075s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(lst_un):\n",
    "#your code here\n",
    "    empty_list = []\n",
    "    for item in lst_un:\n",
    "        if item not in empty_list:\n",
    "            empty_list.append(item)\n",
    "    return empty_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.145s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "#your code here \n",
    "    freq_dict = {}\n",
    "    for item in arr:\n",
    "        if item not in freq_dict:\n",
    "            freq_dict[item] = 0\n",
    "    for item in arr:\n",
    "        if item in freq_dict:\n",
    "            freq_dict[item] += 1\n",
    "    \n",
    "    maxval = 0\n",
    "    for element in freq_dict.keys():\n",
    "        counter += 1\n",
    "        if element > maxval:\n",
    "            maxval = element\n",
    "\n",
    "    keys_list = list(freq_dict.keys())\n",
    "    values_list = list(freq_dict.values())\n",
    "\n",
    "    highest_value = greatest(values_list)\n",
    "\n",
    "    index_of_highest_value = values_list.index(highest_value)\n",
    "    return keys_list[index_of_highest_value]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\PC\\OneDrive\\Documentos\\GitHub\\lab-functions-en\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\PC\\AppData\\Local\\Temp\\ipykernel_11364\\3188611018.py\", line 13, in mode_counter\n",
      "    counter += 1\n",
      "    ^^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'counter' where it is not associated with a value\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.067s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def st_dev(list_sd):\n",
    "#your code here\n",
    "    count = 0\n",
    "    s = 0\n",
    "    for i in list_sd:\n",
    "        s += i\n",
    "        count += 1\n",
    "    mean_ls = s / count\n",
    "\n",
    "    offset = 0\n",
    "    for i in list_sd:\n",
    "        offset += (i - mean_ls)**2\n",
    "    sd = (offset / (count - 1))**0.5\n",
    "    return sd\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.085s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once. Mind that the strings may contain characters that are not letters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "#your code here\n",
    "    alphabet = \"abcdefghijklmnopqrstuvwxyz\"\n",
    "    lower_case_string = string.lower()\n",
    "    letter_check = True\n",
    "    for letter in alphabet:\n",
    "        if letter not in lower_case_string:\n",
    "            letter_check = False\n",
    "        \n",
    "    return letter_check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "..............................\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.020s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "#your code here\n",
    "    words = []  # List to store words\n",
    "    word = \"\"   # Temporary variable to build words manually\n",
    "\n",
    "    # Manually split words using ',' as separator\n",
    "    for char in string:\n",
    "        if char == ',':  # If we hit a comma, store the current word\n",
    "            words.append(word)\n",
    "            word = \"\"  # Reset word for next entry\n",
    "        else:\n",
    "            word += char  # Build word character by character\n",
    "\n",
    "    words.append(word)  # Append the last word\n",
    "\n",
    "    # Sort words alphabetically\n",
    "    sorted_words = sorted(words)\n",
    "\n",
    "    # Manually rebuild the string without `join()`\n",
    "    sorted_string = \"\"\n",
    "    for i in range(len(sorted_words)):\n",
    "        sorted_string += sorted_words[i]\n",
    "        if i < len(sorted_words) - 1:  # Add comma except for the last word\n",
    "            sorted_string += ','\n",
    "\n",
    "    return sorted_string\n",
    "        \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.069s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(password):\n",
    "#your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
