{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def greater(a,b):\n",
    "    if a > b:\n",
    "        return a\n",
    "    else:\n",
    "        return b\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.034s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#your code here\n",
    "greater(2,3)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 141,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def greatest(num_list):\n",
    "    if len(num_list) ==0:\n",
    "        return \"None\"\n",
    "    greatest_num = num_list[0] #assigning greatest num to the first entry to have a variable to store the greatest num\n",
    "\n",
    "    for num in num_list:\n",
    "        if num > greatest_num:\n",
    "           greatest_num = num\n",
    "\n",
    "    return greatest_num\n",
    "        \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 145,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^\n",
      "TypeError: 'int' object is not callable\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.052s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest([11,2,3]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'function'>\n"
     ]
    }
   ],
   "source": [
    "print(type(greatest))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3"
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# This will test your function \n",
    "greatest([1,2,3])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def sum_all(lst):\n",
    "\n",
    "    if not isinstance(lst, list):\n",
    "        print(\"Error: instance must be a list\")\n",
    "        return\n",
    "\n",
    "    result = 0\n",
    "\n",
    "    for num in lst:\n",
    "        result += num\n",
    "    return result\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "print(sum_all([1,2,3]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(lst):\n",
    "    if not isinstance(lst, list):\n",
    "        print(\"Error: instance must be a list\")\n",
    "        return\n",
    "\n",
    "    result = 1\n",
    "\n",
    "    for num in lst:\n",
    "        result*=num\n",
    "    return result\n",
    "#your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 147,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.029s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "36\n"
     ]
    }
   ],
   "source": [
    "print(mult_all([3,3,4]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": [
    "def oper_all(lst):\n",
    "\n",
    "    if not isinstance (lst, list):\n",
    "        print(\"Error: instance must be a list\")\n",
    "\n",
    "    result_add = 0\n",
    "    result_mult = 1\n",
    "\n",
    "    for num in lst:\n",
    "        result_add +=num\n",
    "        result_mult*=num\n",
    "    return result_add, result_mult\n",
    "#your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(12, 60)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "print(oper_all([3,4,5]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def factorial(n):\n",
    "\n",
    "    result = 1\n",
    "\n",
    "    for num in range(n,0,-1):\n",
    "        result*= num\n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#factorial formula\n",
    "#n! = n * ( n - 1 ) *...*1\n",
    "\n",
    "# This code defines a function called \"factorial\" which takes an input \"n\". The function uses a for loop to iterate through the range of numbers \n",
    "# from 1 to n+1. For each number in that range, it multiplies the current value of x by the number in the range. At the end of the loop, \n",
    "# the function returns the final value of x, which will be the factorial of the input number \"n\".\n",
    "\n",
    "# The Factorial of a positive integer n is the product of all positive integers less than or equal to n. \n",
    "# For example, the factorial of 6 (written \"6!\") is 6 * 5 * 4 * 3 * 2 * 1 = 720.\n",
    "\n",
    "# So this function takes an input of any positive integer, and returns the factorial of that number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "720"
      ]
     },
     "execution_count": 72,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "factorial(6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 151,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.029s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(lst):\n",
    "    if not isinstance(lst, list):\n",
    "        print(\"Error: instance must be a list\")\n",
    "\n",
    "    single_dict = {}\n",
    "\n",
    "    for i in lst:\n",
    "        single_dict[i] = single_dict.get(i)\n",
    "    single_values = list(single_dict)\n",
    "    return single_values\n",
    "#your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n"
     ]
    }
   ],
   "source": [
    "print(unique([1,2,2,3,4,4,5,5,6,7,8,8,9,9,10]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 152,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.075s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(lst):\n",
    "    if not isinstance(lst, list):\n",
    "        print(\"Error: instance must be a list.\")\n",
    "        return\n",
    "        \n",
    "    freq_dict = {}\n",
    "    for num in lst:\n",
    "        freq_dict[num] = freq_dict.get(num,0)+1\n",
    "    return freq_dict\n",
    "#your code here\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(mode_counter([3,3,4]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def st_dev(list_sd):\n",
    "    if not isinstance(list_sd, list):\n",
    "        print(\"Error: instance must be a list\")\n",
    "        return\n",
    "\n",
    "    values_dict = {} #dictionary to store the intergers from the list\n",
    "\n",
    "    for num in list_sd:\n",
    "        values_dict[num] = values_dict.get(num)\n",
    "        list_values = list(values_dict) #transforming the dictionary into a list. The list_values stores the single values of the list.\n",
    "\n",
    "    count = len(list_values) #the count stores the length of the list which is going to be useful when having to find the mean of the whole list\n",
    "    mean_variable = 0 #creating a mean variable\n",
    "    addition_result = 0 #creating a variable to store the result of addition of the list\n",
    "    \n",
    "    for number in list_values:\n",
    "        addition_result += number #summing the values in the list and storing them into addition_result\n",
    "\n",
    "    if addition_result > 0:\n",
    "        mean_variable = (addition_result/count) #if the result is greater than 0 we can proceed with calculation the mean\n",
    "\n",
    "    variances_dict = {} #dictionary to store the difference between each number and the mean_variable\n",
    "\n",
    "    for number in list_values:\n",
    "        variances_dict[number] = (number - mean_variable)**2 #each number minus the mean_variable\n",
    "        variances_list = list(variances_dict) #transforming the dictionary into a list\n",
    "\n",
    "    tot_squares = 0 #creating a variable to store the result of squaring all of the variables of the variance_list\n",
    "\n",
    "    for number in variances_list:\n",
    "        tot_squares+= number**number #squaring the numbers of the variances_list and adding them into tot_squares\n",
    "\n",
    "    result_division_squared_and_length_list = tot_squares/(count-1)\n",
    "\n",
    "    standard_deviation = result_division_squared_and_length_list ** 0.5\n",
    "\n",
    "    return standard_deviation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 133,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41.27953488110059\n"
     ]
    }
   ],
   "source": [
    "print(st_dev([3,3,4,5]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once. Mind that the strings may contain characters that are not letters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here\n",
    "def pangram(string):\n",
    "    string_splits = []\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 172,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "    words = string.split(\",\")  # Split the string into a list of words\n",
    "    words = [word.strip() for word in words]  # Remove extra spaces\n",
    "    words.sort()  # Sort the list alphabetically\n",
    "    return \", \".join(words)  # Join the sorted words back into a string\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 173,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "apple, banana, cherry, orange\n"
     ]
    }
   ],
   "source": [
    "input_string = \"banana, apple, cherry, orange\"\n",
    "print(sort_alpha(input_string))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 189,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(password):\n",
    "\n",
    "    has_upper = False\n",
    "    has_lower = False\n",
    "    has_digit = False\n",
    "    has_special = False\n",
    "    special_chars = \"!@#$%^&*(),.?\\\":{}|<>\"\n",
    "\n",
    "    # Check if length is at least 8\n",
    "    if len(password) < 8:\n",
    "        return False\n",
    "\n",
    "    \n",
    "    for char in password:\n",
    "        if 'A' <= char <= 'Z':  # Check if uppercase\n",
    "            has_upper = True\n",
    "        elif 'a' <= char <= 'z':  # Check if lowercase\n",
    "            has_lower = True\n",
    "        elif '0' <= char <= '9':  # Check if digit\n",
    "            has_digit = True\n",
    "        elif char in special_chars:  # Check if special character\n",
    "            has_special = True\n",
    "\n",
    "    # Return True only if all conditions are met\n",
    "    return has_upper and has_lower and has_digit and has_special\n",
    "#your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 190,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n"
     ]
    }
   ],
   "source": [
    "print(check_pass(\"Password@123\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 191,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      ".......................................................F............................................\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_pass.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mirko\\Desktop\\Data_Science\\IH_Notebooks\\lab-functions-en\\mod\\testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AssertionError: False != True : Should be True\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.029s\n",
      "\n",
      "FAILED (failures=1)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
